# Generated by Django 3.0.5 on 2020-04-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('place', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromedriver', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=40)),
                ('lot_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('estimate_min_price', models.CharField(max_length=10)),
                ('estimate_max_price', models.CharField(max_length=10)),
                ('lot_currency', models.CharField(max_length=10)),
                ('sold', models.IntegerField()),
                ('sold_price', models.CharField(max_length=10)),
                ('sold_price_dollar', models.IntegerField()),
                ('images', models.CharField(max_length=100)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchapp.Auction')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('urls', models.TextField()),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('auction_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchapp.AuctionHouse')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchapp.AuctionHouse'),
        ),
    ]
