# Generated by Django 5.0.4 on 2024-04-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0001_auction_actual_lots_auction_job_job_process_lot_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='s3_image',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
